# Generated by Django 4.1.13 on 2024-03-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('image', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('price', models.CharField(max_length=500, verbose_name='Цена')),
            ],
        ),
    ]
